### ISSUE TITLE
Missing temp and model directories

### ISSUE THREAD

**Issue by Conradium** [IRedDragonICY/vixevia#2]
**Describe the bug**
It seems like the commit might have excluded 2 important directories. */temp and */model/audio/

**To Reproduce**
1. Clone the repository
2. Run it
3. See error
![image](https://github.com/IRedDragonICY/vixevia/assets/40384712/dc67ce96-6b8f-4ba9-978a-9c7d9619e56a)

**Expected behavior**
A response would be generated with the synthesized TTS.

**Comment by IRedDragonICY** [comment]
Hi @FrostXD05,

Thank you for bringing this issue to our attention. I understand that you're encountering issues due to missing directories, specifically */temp and */model/audio/.

At the moment, the models such as so vits, live2d, and others are not open-sourced and hence are not included in the repository. This is the reason you're unable to find these directories.

As a workaround, I would recommend you to explore [Hugging Face](https://huggingface.co/models) or similar platforms where you can find various pre-trained models that might serve your purpose. You can download and use those models as per your requirement.

I apologize for the inconvenience caused. I'm planning to open-source these models in the future. Please keep an eye on this repository for updates.

**Comment by Conradium** [comment]
Hi @IRedDragonICY ,

Thank you for the reply. I understand now. Do you have a preview of how it should look like?
It would be very great if you can provide me information of directories/files that needs to be there.
I will explore and replace the missing files with the guide.

Thank you.

**Comment by IRedDragonICY** [comment]
model/audio
there 2 files
audio.json
audio.pth

/mode/live2d
add your live2d model here

/temp

**Comment by IRedDragonICY** [comment]
Hi @FrostXD05,

Thank you for your continued interest in our project. Here is the structure and description for the directories/files you asked about:

1. **model/audio:** This directory contains two files:
    - `audio.json`: This file holds the configuration parameters for the audio model.
    - `audio.pth`: This file is the actual trained model.

2. **model/live2d:** This is the directory where you should place your live2d model files.

3. **temp:** This directory is used for temporary storage during the runtime of the program. You can leave it empty.

4. **api_key.txt:** This is the file where you should place your Gemini API key(s). If your project on Vertex AI is billed (not free), one API key should suffice. However, if it's not, you might need more than one key. Here's an example of how it should look:

```
AIdwqe32rjio3wjdxsadwdqdoqpdqodj
AIdowqpkej3porfjfpow3rfjwpfjwoefjfe
AI2353t09jegifjw94jtopwejgpwjgoep4
(example)
```

Please replace the keys above with your actual API keys. Each key should be on a new line.

I'd like to provide you with a temporary preview of how the project should look like when it's set up correctly. Please refer to the image attached below:

![image](https://github.com/IRedDragonICY/vixevia/assets/98265563/88dc4e16-b4e3-4b3f-af8d-d49204cc9a0f)

Please note that this is a temporary layout and may change as the development progresses. Currently, our main focus is on enhancing the functionality of the AI.

I hope this helps. If you have any more questions or encounter any issues, feel free to ask.

**Comment by Conradium** [comment]
Hi, thanks for your response. This will be extremely helpful. Looking forward for the continuation of the project.
